from typing import Any

class Expression:
    def __abs__(self): ...
    def __add__(self, other): ...
    def __bool__(self) -> bool: ...
    def __call__(self, *args, **kwargs): ...
    def __complex__(self) -> Expression: ...
    def __copy__(self) -> Expression: ...
    def __dir__(self) -> Any: ...
    def __enter__(self) -> Expression: ...
    def __eq__(self, other: object) -> bool: ...
    def __exit__(self, *args) -> Expression: ...
    def __float__(self) -> float: ...
    def __floordiv__(self, other): ...
    def __ge__(self, other: object) -> bool: ...
    def __getmetaclass__(self, _) -> Any: ...
    def __gt__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __invert__(self): ...
    def __le__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __matmul__(self, *args, **kwargs): ...
    def __mod__(self, other): ...
    def __mul__(self, x) -> Any: ...
    def __ne__(self, other: object) -> bool: ...
    def __neg__(self): ...
    def __pos__(self): ...
    def __pow__(self, other): ...
    def __radd__(self, other): ...
    def __rfloordiv__(self, other): ...
    def __rmatmul__(self, *args, **kwargs): ...
    def __rmod__(self, other): ...
    def __rmul__(self, other): ...
    def __rpow__(self, other): ...
    def __rsub__(self, other): ...
    def __rtruediv__(self, other): ...
    def __rxor__(self, other): ...
    def __sub__(self, other): ...
    def __truediv__(self, other): ...
    def __xor__(self, other): ...
